// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Okul.Data;

namespace Okul.Migrations
{
    [DbContext(typeof(VeritabaniContext))]
    [Migration("20190522222607_Yapilandir")]
    partial class Yapilandir
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Okul.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kadi")
                        .IsRequired();

                    b.Property<string>("Sifre")
                        .IsRequired();

                    b.Property<string>("Turu");

                    b.HasKey("Id");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("Okul.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama");

                    b.Property<string>("Adi");

                    b.Property<int>("Okulno");

                    b.Property<string>("Resim");

                    b.Property<string>("Soyadi");

                    b.Property<int>("sınıfid");

                    b.HasKey("Id");

                    b.HasIndex("sınıfid");

                    b.ToTable("ogrenciler");
                });

            modelBuilder.Entity("Okul.Models.Sınıf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.HasKey("Id");

                    b.ToTable("siniflar");
                });

            modelBuilder.Entity("Okul.Models.Ogrenci", b =>
                {
                    b.HasOne("Okul.Models.Sınıf", "sinif")
                        .WithMany("ogrencileri")
                        .HasForeignKey("sınıfid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
